# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
- trunk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.10
    architecture: 'x64'
  displayName: 'Use Python 3.10'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade pip-tools
    pip-sync ubuntu64-py310-dev-requirements.txt
  displayName: 'Install prerequisites'

- script: |
    cd back
    pytest --junitxml=junit/test-results.xml
  condition: succeededOrFailed()
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "**/test-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'

- script: |
    pylint back
  condition: succeededOrFailed()
  displayName: 'Run linting (pylint back)'

- script: |
    pylint fabric_utils
  condition: succeededOrFailed()
  displayName: 'Run linting (pylint fabric_utils)'

- script: |
    pylint fabfile.py
  condition: succeededOrFailed()
  displayName: 'Run linting (pylint fabfile.py)'

- script: |
    fab -l
  condition: succeededOrFailed()
  displayName: 'Run Fabric (fab -l)'

- script: |
    cd front
    npm install --location=global npm@9
    npm install --location=global @angular/cli
    npm ci
  displayName: 'Install required packages (npm install)'

- script: |
    cd front
    npm run-script build
  displayName: 'Compile frontend app (npm run-script build)'

- script: |
    cd front
    npm run-script test-headless
  displayName: 'Run tests (ng test)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TESTS.xml'

- script: |
    cd front
    npm run-script lint
  displayName: 'Run linting (ng lint)'

