[project]
name = "BaseDjangoAngular"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "Django==6.0.2",
    "dealer",
    "django-allauth[headless]",
    "django-environ",
    "psycopg[binary]>=3.0.0",
]

[dependency-groups]
dev = [
    "Fabric",
    "plush-fabric",
    "colorama",
    "pylint",
    "pylint-django",
    "pytest",
    "pytest-django",
]
